### ISSUE TITLE
Latent test failures surfaced by #4814 coverage fix: processStreamChunk not exposed, truncateOutput returns undefined for null fields

### ISSUE THREAD

**Issue by trek-e** [gsd-build/gsd-2#4854]
Ref #4814. The coverage fix in that PR activated 7 previously-orphan test files, which surfaced **4 real failures** that CI had been silently passing over.

## Observed failures

Full run: `cd packages/native && npm test`. After the #4814 fix the runner executes 211 top-level tests; 4 fail.

### 1–3. `stream-process.test.mjs` — `native.processStreamChunk` is not a function

All three tests in `processStreamChunk`:

- `processes a single chunk without state`
- `processes multiple chunks passing state between calls`
- `state fields are plain arrays, not Buffers`

Fail at `dist/stream-process/index.js:30` with:

```
TypeError: native_js_1.native.processStreamChunk is not a function
```

The TS wrapper (`src/stream-process/index.ts:41`) expects the native binary to export `processStreamChunk`, but the built `@gsd/native` binary does not. Either:
- the Rust side never exposed this symbol, and the wrapper + tests were written speculatively, OR
- a rename / refactor on the Rust side dropped the export without updating `index.ts`.

Regression-guard value of these tests (per the authoring commit `148a5aa3a`: "napi state-array crash") is currently zero.

### 4. `truncate.test.mjs` — `truncateOutput` `no truncation when fits`

```js
const r = native.truncateOutput("small", 100);
assert.equal(r.message, null);  // fails — actual: undefined
```

The TS / N-API side returns `undefined` for the optional `message` field when there is no truncation; the test expects `null`. Either:
- the napi mapping should produce `null` for `Option::None`, OR
- the test should accept `undefined`.

The convention in the rest of the codebase (see `stream-process.test.mjs:18` asserting `Array.isArray(result.state.utf8Pending)`) is to return concrete plain values rather than `undefined`, so the likely fix is on the Rust side: emit `null` explicitly for None. Second-order test failures for the tail/head/per-line/balanced branches follow the same pattern.

## Why this matters

The original authoring PRs (`148a5aa3a` for stream-process, the truncate PR) added these tests alongside their feature work. Because #4814's hardcoded list never included them, CI never reported the failures. The authors shipped tests that pass in their local run (after the native build produces the exports), but any subsequent Rust refactor that changes the symbol or napi shape goes undetected.

## Fix plan

- [ ] Investigate `native/src/lib.rs` (or wherever the NAPI exports are defined) for `processStreamChunk`. Add or re-expose the export; rebuild `@gsd/native`; rerun the 3 tests.
- [ ] For `truncateOutput`: fix the Rust `Option<String>` serialization to emit `null` rather than omit the key (napi_rs default behaviour with `Option<T>` is usually `null`, so this may be a field-attribute issue).
- [ ] Re-run `npm test -w @gsd/native` — must show 4 more passes than before.

## Blame

Per audit in #4814, these files live under `src/__tests__/` and were authored in PRs that did not update `packages/native/package.json`'s hardcoded test list. The absence of CI coverage is the upstream cause; the failing behaviour is the real bug.

Does **not** block #4814's coverage fix from landing — that fix is what surfaced these, and shipping it unblocks the chain of fixes.

**Comment by trek-e** [comment]
[triage-rca-v1]

### Rubber-duck diagnosis summary
- **Observed symptom**: Latent test failures surfaced by #4814 coverage fix: processStreamChunk not exposed, truncateOutput returns undefined for null fields
- **Likely code area(s)**: area: native
- **Root-cause hypothesis**: platform-specific process/path semantics differ from POSIX assumptions (spawn/path/stdio handling).

### Diagnose plan (confirm/falsify)
1. Reproduce with a minimal deterministic loop (single failing path).
2. Instrument one boundary at a time around the suspected transition/parser/path normalization seam.
3. Verify whether failure is input-shape drift vs state-ordering drift.
4. Lock with a regression test at the real call-site seam (not source-grep).

Please attach exact version, minimal repro steps, and logs if behavior still reproduces on latest.

**Comment by jeremymcs** [comment]
### Issue evaluation - needs review

Issue: [Latent test failures surfaced by #4814 coverage fix: processStreamChunk not exposed, truncateOutput returns undefined for null fields](https://github.com/gsd-build/gsd-2/issues/4854)

Needs maintainer review because the issue appears larger than a surgical fix and may have broad blast radius.

Confidence: high (75%)

**Safety flags**
- privileged-area
- broad-blast-radius

**Labels applied**
- `needs-maintainer-review`
- `large-scope`

**Comment by jeremymcs** [comment]
Closing as part of a stale-issue sweep — this report predates the GSD 3.0 release.

If you're still hitting this on 3.0, please upgrade and reopen the issue with a fresh repro. Thanks!
