### ISSUE TITLE
gsd_decision_save crashes: adapter.transaction is not a function (regression from #3185 fix)

### ISSUE THREAD

**Issue by curtiswang96** [gsd-build/gsd-2#3326]
## Problem

`gsd_decision_save` crashes with `adapter.transaction is not a function` on every invocation. The tool is completely unusable — no decisions can be saved.

## Root Cause

The fix for #3185 (parallel race condition on `nextDecisionId`) introduced `adapter.transaction()` usage in `db-writer.js:222`:

```js
// db-writer.js:222
const id = adapter.transaction(() => {
    const row = adapter
        .prepare('SELECT MAX(CAST(SUBSTR(id, 2) AS INTEGER)) as max_num FROM decisions')
        .get();
    // ... atomic ID computation + insert
})();
```

However, `createAdapter()` in `gsd-db.js:76` wraps the raw `better-sqlite3` Database object and only exposes three methods — `exec`, `prepare`, and `close`:

```js
// gsd-db.js:76
function createAdapter(rawDb) {
    const db = rawDb;
    // ...
    return {
        exec(sql) { db.exec(sql); },
        prepare(sql) { /* cached */ },
        close() { stmtCache.clear(); db.close(); },
        // ← .transaction() is NOT exposed
    };
}
```

The raw `better-sqlite3` Database has `.transaction()`, but the adapter wrapper strips it. The `_getAdapter()` export returns this wrapper, so `db-writer.js` gets an object without `.transaction()`.

## Expected Behavior

`createAdapter` should expose `.transaction()` so that `saveDecisionToDb` (and any future caller) can use atomic transactions via the adapter:

```js
return {
    exec(sql) { db.exec(sql); },
    prepare(sql) { /* ... */ },
    close() { /* ... */ },
    transaction(fn) { return db.transaction(fn); },  // ← ADD
};
```

Alternatively, `db-writer.js` could use the module-level `gsd-db.transaction()` export (line 750) which already handles re-entrancy — but the adapter should still expose `.transaction()` for consistency since callers reasonably expect it.

## Environment

- GSD version: 2.58.0
- Affected file: `dist/resources/extensions/gsd/gsd-db.js` (line 76, `createAdapter`)
- Caller: `dist/resources/extensions/gsd/db-writer.js` (line 222, `saveDecisionToDb`)
- Regression introduced by: fix for #3185

## Reproduction

1. Run any GSD workflow that triggers `gsd_decision_save` (e.g. `plan-milestone`)
2. Tool crashes with: `Error saving decision: adapter.transaction is not a function`

No workaround exists short of patching the installed `gsd-db.js`.

## Forensic Evidence

- Error message: `adapter.transaction is not a function`
- `createAdapter()` return object has no `transaction` property
- `better-sqlite3` raw DB object does have `.transaction()`
- `gsd-db.js` line 750 exports a standalone `transaction()` function that uses `currentDb.exec("BEGIN"/"COMMIT"/"ROLLBACK")` — this works but `db-writer.js` doesn't use it
- The `adapter.transaction()` call was added as the recommended fix in #3185's issue body

---
*Auto-generated by `/gsd forensics`*
