### ISSUE TITLE
CI broken since #4187: incremental tsc cache skips url-utils.js, breaking all open PRs

### ISSUE THREAD

**Issue by NilsR0711** [gsd-build/gsd-2#4195]
## Summary

Every open PR currently fails `CI / build` and `CI / integration-tests`. The breakage started with the merge of #4187 at ~16:24 UTC on 2026-04-14 and affects all PRs branched from or targeting `main` since then.

## Affected PRs (confirmed)

| PR | build failures | integration failures |
|----|---------------|---------------------|
| #4188 | 2–4 | 44 |
| #4190 | 2 | 44 |
| #4192 | 4 | 44 |
| #4193 | 4 | 44 |
| #4194 | 2 | 44 |

All PRs fail with **identical** test lists. The variance in build failure count (2 vs 4) is caused by cache slot differences, not PR content.

## Symptoms

**`CI / build` (unit tests):**
```
✖ loader sets all 4 GSD_ env vars and PI_PACKAGE_DIR
  expected >=10 extensions, found 0–5

✖ initResources syncs extensions, agents, and skills to target dir
  browser-tools extension synced
```

**`CI / integration-tests` (44 tests, all with the same root cause):**
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module
  '.../dist/resources/extensions/search-the-web/url-utils.js'
  imported from .../dist/security-overrides.js
```

## Root cause

PR #4187 introduced two changes that interact badly with `copy-resources.cjs`:

### 1. `tsconfig.json` gains `"incremental": true`

`tsconfig.resources.json` extends `tsconfig.json` and does not override `incremental`. It now also compiles with `incremental: true`, causing TypeScript to write `tsconfig.resources.tsbuildinfo` in the **project root** after every `tsc --project tsconfig.resources.json` run.

### 2. CI now caches `*.tsbuildinfo` and `dist/`

```yaml
- name: Cache TypeScript incremental state
  uses: useblacksmith/cache@v5
  with:
    path: |
      *.tsbuildinfo
      packages/*/*.tsbuildinfo
      dist
      packages/*/dist
    key: tsbuild-${{ runner.os }}-${{ hashFiles(...) }}
    restore-keys: |
      tsbuild-${{ runner.os }}-
```

### 3. How they interact

`copy-resources.cjs` (called from `npm run build:core`) does this:

```js
rmSync('dist/resources', { recursive: true, force: true }); // deletes dist/resources
spawnSync(process.execPath, [tscBin, '--project', 'tsconfig.resources.json'], ...);
copyNonTsFiles('src/resources', 'dist/resources');
```

Step 1 deletes `dist/resources` — but `tsconfig.resources.tsbuildinfo` lives in the **project root** and is NOT deleted.

Step 2 runs `tsc` with incremental mode. TypeScript reads the cached (stale) `tsconfig.resources.tsbuildinfo`, considers its recorded outputs up to date, and **skips re-emitting** output files — including `url-utils.js`. The file is never written to `dist/resources`.

Step 3 copies only non-TS assets; `.js` files must come from tsc.

The stale `.tsbuildinfo` is seeded from the CI cache on every run via the partial `restore-keys: tsbuild-${{ runner.os }}-` fallback and perpetuates across all subsequent builds.

You can reproduce this locally:

```bash
tsc --project tsconfig.resources.json   # generates tsconfig.resources.tsbuildinfo
rm -rf dist/resources                   # simulates copy-resources.cjs
tsc --project tsconfig.resources.json   # incremental: skips output
ls dist/resources/extensions/search-the-web/
# → only extension-manifest.json — url-utils.js missing
```

## Fix options

**Option A — disable incremental in `tsconfig.resources.json` (minimal, safe):**

```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "incremental": false,
    "rootDir": "src/resources",
    "outDir": "dist/resources",
    ...
  }
}
```

Extensions compile fast and already benefit from the restored `dist/` cache. Incremental state here adds no meaningful build-time benefit.

**Option B — move the `.tsbuildinfo` inside `dist/` so it gets cleaned up:**

Add `"tsBuildInfoFile": "dist/tsconfig.resources.tsbuildinfo"` to `tsconfig.resources.json`. Since `copy-resources.cjs` deletes `dist/resources` (not all of `dist/`), update it to also delete `dist/tsconfig.resources.tsbuildinfo` before running tsc.

**Option C — delete the `.tsbuildinfo` in `copy-resources.cjs` before running tsc:**

```js
rmSync('dist/resources', { recursive: true, force: true });
rmSync('tsconfig.resources.tsbuildinfo', { force: true }); // add this
spawnSync(process.execPath, [tscBin, '--project', 'tsconfig.resources.json'], ...);
```

Option A is the lowest-risk fix. Option C is a targeted patch that doesn't require tsconfig changes.

## Timeline

| Time (UTC) | Event |
|-----------|-------|
| 15:29 | #4186 merges → CI green |
| 16:24 | **#4187 merges → CI broken** |
| 17:12 | #4188 merges on top of broken main → CI broken |
| ongoing | All new PRs inherit the broken CI state |

**Comment by jeremymcs** [comment]
Yup. redoing alot of the CI currently.

**Comment by NilsR0711** [comment]
Fixed by #4196 (merged). Disabling  in  (Option A) prevents stale build info from causing skipped re-emit after  cleanup.
