### ISSUE TITLE
v2.9.0 startup triggers Error: Cannot find module './defaults.json'

### ISSUE THREAD

**Issue by matech-01** [gsd-build/gsd-2#234]
MacOS... after updating to v2.9.0, starting gsd triggers error below...

node:internal/modules/cjs/loader:1447
  const err = new Error(message);
              ^

Error: Cannot find module './defaults.json'
Require stack:
- /opt/homebrew/lib/node_modules/gsd-pi/node_modules/@gsd/pi-coding-agent/dist/core/lsp/config.js
