### ISSUE TITLE
v2.28.0: subagent extension fails to load — broken relative import to bundled-extension-paths.js

### ISSUE THREAD

**Issue by jacoblewisau** [gsd-build/gsd-2#1087]
### GSD Version
2.28.0 (upgraded from 2.27.0)

### Environment
- macOS (Darwin 24.6.0, arm64)
- Node.js v25.2.1
- Installed via: `npm install -g gsd-pi`

### Error Message

```
[gsd] Extension load error: Failed to load extension: Cannot find module '../../../bundled-extension-paths.js'
Require stack:
- /Users/<user>/.gsd/agent/extensions/subagent/index.ts
```

### Description

After updating from 2.27.0 to 2.28.0, the subagent extension fails to load on every launch. The error persists even after clearing `~/.gsd/agent/extensions/` and letting GSD regenerate them.

The issue is a broken relative import at `~/.gsd/agent/extensions/subagent/index.ts:26`:

```typescript
import { parseBundledExtensionPaths } from "../../../bundled-extension-paths.js";
```

This path resolves to `~/.gsd/bundled-extension-paths.js`, which doesn't exist. The actual file lives in the npm package at:

```
/opt/homebrew/lib/node_modules/gsd-pi/dist/bundled-extension-paths.js
```

The extension was written assuming it runs from inside the npm package tree, but GSD copies extensions to `~/.gsd/agent/extensions/` where the relative path no longer resolves.

### Workaround

Symlink the missing module:

```bash
ln -s /opt/homebrew/lib/node_modules/gsd-pi/dist/bundled-extension-paths.js ~/.gsd/bundled-extension-paths.js
```

### Expected Behavior

Extensions copied to `~/.gsd/agent/extensions/` should either:
1. Use absolute imports to the installed package
2. Have the dependency copied alongside them
3. Resolve the import relative to the npm package root rather than the file's current location

### Reproduction

```bash
npm update -g gsd-pi   # Upgrade to 2.28.0
gsd                     # Error on launch
```

Clearing and regenerating extensions does not fix it — the same broken import is written again.

**Comment by jeremymcs** [comment]
## Investigation & Fix

This issue has been identified and a fix already exists.

### Root Cause

The subagent extension (`~/.gsd/agent/extensions/subagent/index.ts`) imports `parseBundledExtensionPaths` via a relative path:

```typescript
import { parseBundledExtensionPaths } from "../../../bundled-extension-paths.js";
```

This resolves correctly in the source tree (`src/resources/extensions/subagent/` → `src/bundled-extension-paths.ts`), but when GSD syncs extensions to `~/.gsd/agent/extensions/` at runtime, the path `../../../bundled-extension-paths.js` resolves to `~/.gsd/bundled-extension-paths.js` which doesn't exist.

### Fix

The fix (commit `ebfe5e17`) inlines the trivial `parseBundledExtensionPaths` logic directly in the subagent extension, eliminating the broken cross-tree import entirely. Instead of importing and calling the function, the subagent now performs the simple string split inline.

### Current Status

The fix is currently part of PR #980 (`feat/add-specialist-agents`), which is a larger feature PR still in review. We'll cherry-pick the fix into a standalone PR to get it merged independently so the fix ships without waiting for the full feature set.

### Workaround (until fix ships)

As the reporter noted, symlinking works:

```bash
ln -s $(npm root -g)/gsd-pi/dist/bundled-extension-paths.js ~/.gsd/bundled-extension-paths.js
```

**Comment by trek-e** [comment]
Duplicate of #1123, which was already fixed in commit ebfe5e17 (inlined bundled extension path parsing). Closing as resolved.

**Comment by jeremymcs** [comment]
## Update: Fix is already on main

After pulling latest main (15 new commits), the fix is already present. The broken `parseBundledExtensionPaths` import has been replaced with an inline implementation at line 335 of `src/resources/extensions/subagent/index.ts`:

```typescript
const bundledPaths = (process.env.GSD_BUNDLED_EXTENSION_PATHS ?? "").split(path.delimiter).map(s => s.trim()).filter(Boolean);
```

The fix landed on main via PR #1052 (perf: skip initResources when version matches). This will ship in the next release. Closing.
